#!/bin/sh

# This allows macOS dropping to the dock icon, etc.
# See: https://lists.apple.com/archives/java-dev/2012/Nov/msg00019.html
export CFProcessPath="$0"

APP_CONTENTS="$(dirname "$0")/.."

JAVA_HOME="$APP_CONTENTS/PlugIns/jre.bundle/Contents/Home"

exec "$JAVA_HOME/bin/java" \
     -Xdock:name=OmegaT \
     -Xdock:icon="$APP_CONTENTS/Resources/OmegaT.icns" \
     -jar "$APP_CONTENTS/Java/OmegaT.jar" \
     --config-file="$APP_CONTENTS/Resources/Configuration.properties"
