plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = omegatModule.providedCoreLibsDir

dependencies {
    compileOnly(project(':'))
    if (file(providedCoreLibsDir).directory) {
        compileOnly omegatModule.providedCoreLib('jspecify', 'languagetool-core', 'commons-io', 'icu4j')
        implementation omegatModule.providedModuleLib('language-ja')
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.languagetool.core)
        implementation(libs.languagetool.ja) {
            exclude module: 'languagetool-core'
            exclude module: 'lucene-analysis-kuromoji'
        }
        compileOnly(libs.icu4j)
    }
    testImplementation(libs.languagetool.core)

    testImplementation(libs.junit4)
    testRuntimeOnly(libs.slf4j.jdk14)
    testImplementation(project(':'))

    testImplementation(libs.languagetool.core) {
        exclude module: 'language-all'
    }
    testImplementation(libs.languagetool.ja)
    testImplementation(libs.lucene.analyzers.kuromoji)
    testImplementation(libs.assertj.core)
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.commons.io)
}

test {
    useJUnit()
}
