version: '3'
services:
  server:
    build: test-integration/docker/server
    volumes:
      - keygen:/keys
    tmpfs:
      - /tmp
  client:
    build: test-integration/docker/client
    depends_on:
      - server
    volumes:
      - .:/code
      - keygen:/keys
    tmpfs:
      - /tmp
    environment:
      DURATION: ${DURATION:-2400}
      TYPE: ${TYPE:-GIT}
volumes:
  keygen:
