version: '3'
services:
  keygen:
    build: test-integration/docker/keygen
    volumes:
      - keygen:/keys
  server:
    build: test-integration/docker/server
    expose:
      - "22"
    volumes:
      - keygen:/keys
    depends_on:
      - keygen
  client:
    build: test-integration/docker/client
    depends_on:
      - keygen
      - server
    volumes:
      - .:/code
      - keygen:/keys
    environment:
      DURATION: ${DURATION:-2400}
      REPO: "git@server:omegat-test.git"
volumes:
  keygen: