#!/bin/sh

JENKINS=https://omegat.ci.cloudbees.com

function did_change() {
    if [ -z "$(svn diff --summarize -c "$2" "file://$1")" ]; then
        return 1
    else
        return 0
    fi
}

if did_change "$1/trunk" "$2"; then
    /usr/bin/curl -s $JENKINS/job/omegat-trunk/build?token=REDACTED
    /usr/bin/curl -s $JENKINS/job/sourceforge-svn-git-sync/buildWithParameters?token=REDACTED
fi

if did_change "$1/branches/release-3-6" "$2"; then
   /usr/bin/curl -s $JENKINS/job/omegat-release-3-6/build?token=REDACTED
fi

if did_change "$1/branches/release-3-5" "$2"; then
   /usr/bin/curl -s $JENKINS/job/omegat-release-3-5/build?token=REDACTED
fi

exit 0
