/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2025 Hiroshi Miura
               Home page: https://www.omegat.org/
               Support center: https://omegat.org/support

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
 **************************************************************************/
package org.omegat.cli;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

public final class SubCommands {

    private SubCommands() {
    }

    private static final Map<String, Class<? extends BaseSubCommand>> SUB_COMMAND_ENTRIES = new HashMap<>();

    /**
     * Registers a console command by associating a command name with its corresponding subcommand class.
     * This method adds the specified command to a collection of subcommands, enabling it to be later
     * utilized or executed through the command-line interface.
     *
     * @param name       the subcommand name of the console command to be registered.
     * @param subcommand the class representing the subcommand implementation associated with the given name.
     */
    public static synchronized void registerConsoleCommand(String name, Class<? extends BaseSubCommand> subcommand) {
        SUB_COMMAND_ENTRIES.put(name.toLowerCase(Locale.ENGLISH), subcommand);
    }

    /**
     * Registers a console command by deriving the command name from the specified subcommand class
     * and associating it with the class in the subcommand registry. The command name is automatically
     * generated by removing the "Command" suffix from the class name and converting the result to
     * lowercase.
     *
     * @param subcommand the class representing the subcommand implementation whose name is to be
     *                   derived and registered in the subcommand registry.
     */
    public static synchronized void registerConsoleCommand(Class<? extends BaseSubCommand> subcommand) {
        String name = subcommand.getSimpleName();
        name = name.substring(0, name.length() - "Command".length()).toLowerCase(Locale.ENGLISH);
        registerConsoleCommand(name, subcommand);
    }

    /**
     * Checks if a subcommand with the specified key exists in the registry.
     *
     * @param key the key to check for existence
     * @return true if the subcommand exists, false otherwise
     */
    public static boolean containsCommand(String key) {
        return SUB_COMMAND_ENTRIES.containsKey(key.toLowerCase(Locale.ENGLISH));
    }

    /**
     * Gets the subcommand class associated with the specified key.
     * @param key subcommand key
     * @return subcommand class
     */
    public static Class<? extends BaseSubCommand> getCommand(String key) {
        return SUB_COMMAND_ENTRIES.get(key.toLowerCase(Locale.ENGLISH));
    }

    /**
     * Get all subcommand names.
     * @return set of subcommand names
     */
    public static Set<String> getSubcommandNames() {
        return SUB_COMMAND_ENTRIES.keySet();
    }
}
