/*
 * AboutDialog.java
 *
 * Created on 23 ћарт 2005 г., 22:47
 */

package org.omegat.gui.dialogs;

import java.awt.Frame;
import javax.swing.JDialog;
import org.omegat.util.OStrings;

/**
 * About dialog, showing OmegaT version and information on contributors.
 *
 * @author Maxym Mykhalchuk
 */
public class AboutDialog extends JDialog
{
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form AboutDialog */
    public AboutDialog(Frame parent)
    {
        super(parent, true);
        initComponents();
        versionLabel.setText("OmegaT version "+OStrings.HUMAN_VERSION);
    }
    
    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus()
    {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        licenseButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        versionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        setTitle("About OmegaT");
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.BorderLayout());

        buttonPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Copyright \u00a9 2002-2005 Keith Godfrey et al");
        jLabel2.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        buttonPanel.add(jLabel2, java.awt.BorderLayout.WEST);

        org.openide.awt.Mnemonics.setLocalizedText(licenseButton, "&License");
        licenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseButtonActionPerformed(evt);
            }
        });

        jPanel1.add(licenseButton);

        org.openide.awt.Mnemonics.setLocalizedText(okButton, "&OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jPanel1.add(okButton);

        buttonPanel.add(jPanel1, java.awt.BorderLayout.EAST);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        versionLabel.setIcon(new javax.swing.ImageIcon("D:\\omegat\\src\\org\\omegat\\resources\\OmegaT.gif"));
        org.openide.awt.Mnemonics.setLocalizedText(versionLabel, " OmegaT version 1.4.5");
        versionLabel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        getContentPane().add(versionLabel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)));
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTextArea1.setEditable(false);
        jTextArea1.setFont(versionLabel.getFont());
        jTextArea1.setLineWrap(true);
        jTextArea1.setText("OmegaT is a high performance Java based Computer Assisted Translation tool with fuzzy matching, translation memory, keyword search, glossary term identification, and translation leveraging into updated projects.\n\nOmegaT is originally the work of Keith Godfrey\n\nCode has been contributed by \n  Benjamin Siband\n  Maxym Mykhalchuk (lead developer at the time of this release)\n  Sacha Chua \n  Henry Pijffers\n\nOther contributions by \n  Marc Prior (project coordinator and ASAD manual writer)\n  Jean-Christophe Helary\n  Samuel Murray\n  Dmitry Gabinski (user manual writer at the time of this release) \n  and many, many more very helpful people");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-486)/2, (screenSize.height-402)/2, 486, 402);
    }//GEN-END:initComponents

    private void licenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseButtonActionPerformed
        new LicenseDialog(this).setVisible(true);
    }//GEN-LAST:event_licenseButtonActionPerformed
    
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
    {
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed
        
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
    {
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus)
    {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    // ќбъ€вление переменных - не измен€йте данный код//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton licenseButton;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel versionLabel;
    //  онец объ€влени€ переменных//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
}
