/**************************************************************************
 OmegaT - Java based Computer Assisted Translation (CAT) tool
 Copyright (C) 2002-2004  Keith Godfrey et al
                          keithgodfrey@users.sourceforge.net
                          907.223.2039

 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
**************************************************************************/

package org.omegat.gui.dialogs;

import org.omegat.util.OStrings;

import java.awt.Frame;
import javax.swing.JDialog;

/**
 *
 * @author  Maxym Mykhalchuk
 */
public class MatchingSimilarityDialog extends JDialog
{
	/** Creates new form MatchingSimilarityDialog */
	public MatchingSimilarityDialog(Frame parent, String nearTrash)
	{
		super(parent);
		initComponents();
		value = (int)Math.round( 5 * (Double.parseDouble(nearTrash) - 0.2) );
		similaritySlider.setValue(value);
		pack();
	}
	
	private boolean changed = false;
	/** @return if the user changed similarity coefficient and pressed OK */
	public boolean isChanged()
	{
		return changed;
	}

	private int value;
	/** @return trash number */
	public String getNearTrash()
	{
		switch( value )
		{
			case 0:
				return "0.2";													// NOI18N
			case 1:
				return "0.4";													// NOI18N
			case 2:
			default:
				return "0.6";													// NOI18N
		}
	}
	
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        descriptionText = new javax.swing.JTextArea();
        similaritySlider = new javax.swing.JSlider();
        captionsPanel = new javax.swing.JPanel();
        minLabel = new javax.swing.JLabel();
        normLabel = new javax.swing.JLabel();
        maxLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle(OStrings.getString("MS_TITLE"));
        setModal(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        okButton.setText(OStrings.getString("BUTTON_OK"));
        okButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText(OStrings.getString("BUTTON_CANCEL"));
        cancelButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(buttonPanel, gridBagConstraints);

        descriptionText.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        descriptionText.setEditable(false);
        descriptionText.setFont(maxLabel.getFont());
        descriptionText.setLineWrap(true);
        descriptionText.setText(OStrings.getString("MS_DESCRIPTION"));
        descriptionText.setWrapStyleWord(true);
        descriptionText.setDisabledTextColor(javax.swing.UIManager.getDefaults().getColor("Label.foreground"));
        descriptionText.setEnabled(false);
        descriptionText.setMinimumSize(new java.awt.Dimension(200, 100));
        descriptionText.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        getContentPane().add(descriptionText, gridBagConstraints);

        similaritySlider.setMajorTickSpacing(1);
        similaritySlider.setMaximum(2);
        similaritySlider.setPaintTicks(true);
        similaritySlider.setSnapToTicks(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 10, 0, 10);
        getContentPane().add(similaritySlider, gridBagConstraints);

        captionsPanel.setLayout(new java.awt.GridLayout(2, 3, 30, 0));

        minLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        minLabel.setText(OStrings.getString("MS_LABEL_MIN"));
        captionsPanel.add(minLabel);

        normLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        normLabel.setText(OStrings.getString("MS_LABEL_LOW"));
        captionsPanel.add(normLabel);

        maxLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        maxLabel.setText(OStrings.getString("MS_LABEL_NORMAL"));
        captionsPanel.add(maxLabel);

        jLabel1.setText(OStrings.getString("MS_HINT_MIN"));
        captionsPanel.add(jLabel1);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(OStrings.getString("MS_HINT_LOW"));
        captionsPanel.add(jLabel2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 4, 4);
        getContentPane().add(captionsPanel, gridBagConstraints);

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }//GEN-END:initComponents
	
	private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
	{
		changed = similaritySlider.getValue() != value;
		value = similaritySlider.getValue();
		doClose();
	}//GEN-LAST:event_okButtonActionPerformed
	
	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
	{
		doClose();
	}//GEN-LAST:event_cancelButtonActionPerformed
	
	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
	{
		doClose();
	}//GEN-LAST:event_closeDialog
	
	private void doClose()
	{
		setVisible(false);
		dispose();
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel captionsPanel;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel maxLabel;
    private javax.swing.JLabel minLabel;
    private javax.swing.JLabel normLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JSlider similaritySlider;
    // End of variables declaration//GEN-END:variables
	
}
