# OmegaT default light color scheme
#
# Format is 8-bit RGB or RGBA in hexadecimal (like standard HTML colors)
OmegaT.activeSource=#c0ffc0
OmegaT.source=#c0ffc0
OmegaT.noted=#c0ffff
OmegaT.untranslated=#c0c0ff
OmegaT.translated=#ffff99
OmegaT.nonUnique=#666666
OmegaT.placeholder=#6b6b6b
OmegaT.removeTextTarget=#db0000
OmegaT.nbsp=#888888
OmegaT.whiteSpace=#808080
OmegaT.bidiMarkers=#c80000
OmegaT.paragraphStart=#888888
OmegaT.markComesFromTmMt=#fa8072
OmegaT.markComesFromTmXice=#af76df
OmegaT.markComesFromTmX100pc=#ff9408
OmegaT.markComesFromTmXauto=#ffd596
OmegaT.markComesFromTmXenforced=#ffccff
OmegaT.markComesFromSourceFile=#a0e8c0
OmegaT.replace=#0000ff
OmegaT.languageTools=#0000ff
OmegaT.transTips=#0000ff
OmegaT.spellCheck=#ff0000
OmegaT.terminology=#b84c00
OmegaT.matchesChanged=#0000ff
OmegaT.matchesUnchanged=#007a00
OmegaT.matchesInsActive=#0000ff
OmegaT.matchesInsInactive=#6c6c6c
OmegaT.hyperlink=#0000ff
OmegaT.searchFoundMark=#0000ff
OmegaT.searchReplaceMark=#995c00
OmegaT.notificationMin=#fff2d4
OmegaT.notificationMax=#ff9900
OmegaT.alignerAccepted=#15bb45
OmegaT.alignerNeedsReview=#ff0000
OmegaT.alignerHighlight=#ffff00
OmegaT.alignerTableRowHighlight=#c8c8c8
OmegaT.projectFilesProgressLow=#f0b8b4
OmegaT.projectFilesProgressHigh=#b7d7b7
OmegaT.projectFilesProgressComplete=#b8ccf0
OmegaT.projectFilesCurrentFileForeground=#000000
OmegaT.projectFilesCurrentFileBackground=#c8ddf2
OmegaT.searchFieldErrorText=#ff0000
OmegaT.searchDimmedBackground=#80808080
OmegaT.searchResultBorder=#EED20080
OmegaT.machinetranslateSelectedHighlight=#ffff00
OmegaT.markAltTranslations=#33ffff
OmegaT.activeSourceForeground=#000000
OmegaT.activeTarget=#ffffff
OmegaT.activeTargetForeground=#000000
OmegaT.segmentMarkerForeground=#000000
OmegaT.segmentMarkerBackground=#ffffff
OmegaT.sourceForeground=#000000
OmegaT.notedForeground=#000000
OmegaT.untranslatedForeground=#000000
OmegaT.translatedForeground=#000000
OmegaT.modInfo=#ffffff
OmegaT.modInfoForeground=#000000
OmegaT.glossarySource=#000000
OmegaT.glossaryTarget=#000000
OmegaT.glossaryNote=#000000
OmegaT.matchesDelActive=#000000
OmegaT.matchesDelInactive=#000000
OmegaT.nonUniqueBackground=#f5f5f5
