/**
 * IBM watson translator connector.
 */

plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = rootProject.property('providedCoreLibsDir')

dependencies {
    compileOnly(project(':'))
    if (file(providedCoreLibsDir).directory) {
        compileOnly fileTree(dir: providedCoreLibsDir, includes: ['**/*commons-*.jar', '**/slf4j*.jar',
                                                                  '**/jackson*.jar', '**/jspecify-*.jar'])
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.commons.text)
        // JSON parser
        compileOnly(libs.jackson.core)
        compileOnly(libs.jackson.databind)
        compileOnly(libs.jspecify)
    }
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.jackson.core)
    testImplementation(libs.jackson.databind)
}
