plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = rootProject.property('providedCoreLibsDir')
def providedModuleLibsDir = rootProject.property('providedModuleLibsDir')

dependencies {
    compileOnly(project(':'))
    if (file(providedCoreLibsDir).directory) {
        compileOnly fileTree(dir: providedCoreLibsDir,
                includes: ['**/jspecify-*.jar', '**/languagetool-core-*.jar', '**/commons-io-*.jar'])
        implementation fileTree(dir: providedModuleLibsDir, includes: ['**/language-sv-*.jar'])
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.languagetool.core)
        implementation(libs.languagetool.sv) {
            exclude module: 'languagetool-core'
        }
        compileOnly(libs.lucene.analyzers.common)
    }
    testImplementation(libs.junit4)
    testImplementation(libs.assertj.core)
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.commons.io)
    testImplementation(libs.languagetool.core)
    testImplementation project(":spellchecker:lucene")
}

test {
    dependsOn tasks.withType(Jar)
    dependsOn project(":spellchecker:lucene").tasks.withType(Jar)
}
