#!/bin/bash

# readlink follows any symbolic links to get the real file
REALOMEGATPATH=`dirname "$(readlink -nf $0)"`

JAVA="java"
BUNDLED_JAVA="${REALOMEGATPATH}/jre/bin/java"
[ -f "${BUNDLED_JAVA}" ] && JAVA="${BUNDLED_JAVA}"

version=$("$JAVA" -version 2>&1 | awk -F '"' '/version/ {print $2}' | awk -F '.' '{print $1}')
if [[ "${OPENJFX_CLASSPATH}" ]] && [[ "${version}" == "11" ]]; then
  "${JAVA}" --module-path ${OPENJFX_CLASSPATH} --add-modules=javafx.base,javafx.controls,javafx.swing,javafx.web -jar -Xmx1024M "${REALOMEGATPATH}/@JAR_SUBST@" "$@"
else
  "${JAVA}" -jar -Xmx1024M "${REALOMEGATPATH}/@JAR_SUBST@" "$@"
fi
