#!/usr/bin/env bash

# This accept environment variable USBDEV which is smartcard device
# USBDEV="--device /dev/bus/usb/004/004"

relpaths() {
    for arg in "$@"; do printf -- "%s\n" "${arg#$PWD/}"; done
}

bindpaths() {
    for arg in $(relpaths "$@"); do
        if [ -e "$arg" ] && [[ "$arg" == /* ]]; then
            printf -- "-v %s:%s" "$arg" "$arg"
        fi
    done
}

CMD="$(type -p docker)" && $CMD info >/dev/null 2>1 || CMD="$(type -p nerdctl)" && $CMD info >/dev/null || false
echo Select container CLI: $CMD

# build container image
CTX=$(mktemp -d)
cat <<__EOF__ > $CTX/Dockerfile
FROM debian:bookworm-slim
LABEL authors="miurahr"
USER root
RUN apt-get update && apt-get install -y --no-install-recommends osslsigncode && rm -rf /var/lib/apt/lists/*
WORKDIR /work
__EOF__
$CMD build -t omegatorg/osslsigncode $CTX

if [[ -z "${USBDEV}" ]]; then
  exec $CMD run --rm -i \
      -v "$PWD":/work $(bindpaths "$@") \
      --pull=never omegatorg/osslsigncode \
      osslsigncode $@
else
  exec $CMD run --rm -i \
      -v "$PWD":/work $(bindpaths "$@") \
      --privileged --device $USBDEV \
      --pull=never omegatorg/osslsigncode \
      osslsigncode $@
fi

