#!/usr/bin/env python3
# OmegaT - Computer Assisted Translation (CAT) tool
#          with fuzzy matching, translation memory, keyword search,
#          glossaries, and translation leveraging into updated projects.
#
# Copyright (C) 2026 OmegaT contributors
#               Home page: https://www.omegat.org/
#               Support center: https://omegat.org/support
#
# This file is part of OmegaT.
#
# OmegaT is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OmegaT is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""Render editor-colors.svg: every Styles.EditorColor value of the bundled
flat themes, light and dark side by side, once in enum order and once sorted
by hue.

Input CSVs come from ColorDump.java (same directory). From a built
distribution (build/install/OmegaT):

  javac -cp "OmegaT.jar:lib/*:modules/theme-omegat.jar" -d /tmp ColorDump.java
  java -Djava.awt.headless=true -cp "/tmp:OmegaT.jar:lib/*:modules/theme-omegat.jar" \
      ColorDump org.omegat.gui.theme.DefaultFlatLightTheme > colors-Light.csv
  java -Djava.awt.headless=true -cp "/tmp:OmegaT.jar:lib/*:modules/theme-omegat.jar" \
      ColorDump org.omegat.gui.theme.DefaultFlatDarkTheme > colors-Dark.csv
  ./generate_editor_colors_svg.py colors-Light.csv colors-Dark.csv editor-colors.svg
"""
import colorsys
import sys

GPL_COMMENT = """<!--
 OmegaT - Computer Assisted Translation (CAT) tool

 Copyright (C) 2026 OmegaT contributors
 Home page: https://www.omegat.org/

 This file is part of OmegaT, generated by generate_editor_colors_svg.py.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->"""

ROW_H = 17
PANEL_W = 330
PANEL_GAP = 14
TOP = 74
NAME_X = 26

def read_csv(path):
    rows = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line:
                name, _key, value = line.split(",")
                rows.append((name, value))
    return rows

def hue_key(entry):
    value = entry[1]
    r, g, b = (int(value[i:i + 2], 16) / 255.0 for i in (0, 2, 4))
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    achromatic = s < 0.08
    return (0, v, 0) if achromatic else (1, h, v)

def swatch(value, x, y):
    fill = "#" + value[:6]
    opacity = "" if len(value) == 6 else ' fill-opacity="%.3f"' % (int(value[6:8], 16) / 255.0)
    return ('<rect x="%d" y="%d" width="13" height="13" rx="2" fill="%s"%s '
            'stroke="#888888" stroke-width="0.5"/>' % (x, y, fill, opacity))

def panel(x, title, rows, dark):
    label = "#dddddd" if dark else "#222222"
    out = ['<rect x="%d" y="%d" width="%d" height="%d" rx="6" fill="%s"/>'
           % (x, TOP - 24, PANEL_W, len(rows) * ROW_H + 34, "#3c3f41" if dark else "#fdfdfd"),
           '<text x="%d" y="%d" font-size="12" font-weight="bold" fill="%s">%s</text>'
           % (x + 10, TOP - 7, label, title)]
    for i, (name, value) in enumerate(rows):
        y = TOP + i * ROW_H
        out.append(swatch(value, x + 8, y + 2))
        opacity = "" if len(value) == 6 else ' fill-opacity="%.3f"' % (int(value[6:8], 16) / 255.0)
        out.append('<text x="%d" y="%d" font-size="9.5" font-family="Menlo, Consolas, monospace" '
                   'fill="#%s"%s>%s</text>' % (x + NAME_X, y + 12, value[:6], opacity, name))
        out.append('<text x="%d" y="%d" font-size="9" font-family="Menlo, Consolas, monospace" '
                   'fill="%s" text-anchor="end">#%s</text>'
                   % (x + PANEL_W - 8, y + 12, "#9aa0a3" if dark else "#777777", value))
    return "\n".join(out)

def main():
    light = read_csv(sys.argv[1])
    dark = read_csv(sys.argv[2])
    panels = [
        ("Light - enum order", light, False),
        ("Light - by hue", sorted(light, key=hue_key), False),
        ("Dark - enum order", dark, True),
        ("Dark - by hue", sorted(dark, key=hue_key), True),
    ]
    width = 20 + 4 * (PANEL_W + PANEL_GAP)
    height = TOP + len(light) * ROW_H + 40
    parts = ['<?xml version="1.0" encoding="UTF-8"?>', GPL_COMMENT,
             '<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" '
             'viewBox="0 0 %d %d" font-family="Helvetica, Arial, sans-serif">'
             % (width, height, width, height),
             '<rect width="%d" height="%d" fill="#ffffff"/>' % (width, height),
             '<text x="20" y="28" font-size="16" font-weight="bold" fill="#222222">'
             'OmegaT editor colours - effective theme defaults (Styles.EditorColor)</text>']
    for i, (title, rows, is_dark) in enumerate(panels):
        parts.append(panel(20 + i * (PANEL_W + PANEL_GAP), title, rows, is_dark))
    parts.append('</svg>')
    with open(sys.argv[3], "w") as f:
        f.write("\n".join(parts) + "\n")

if __name__ == "__main__":
    main()
