plugins {
    id 'org.omegat.module'
}

dependencies {
    compileOnly(project.rootProject)
    if (providedCoreLibsDir.directory) {
        compileOnly fileTree(dir: providedCoreLibsDir,
                includes: ['**/jspecify-*.jar', '**/languagetool-core-*.jar', '**/commons-io-*.jar'])
        implementation providedModuleLib('language-zh')
        runtimeOnly providedModuleLib('hanlp-portable')
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.languagetool.core)
        implementation(libs.languagetool.zh) {
            exclude module: 'languagetool-core'
        }
    }
    testImplementation(libs.junit4)
    testImplementation(libs.assertj)
    testImplementation(testFixtures(project.rootProject))
    testImplementation(libs.languagetool.core)
    testImplementation(libs.commons.io)
}
