plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = rootProject.property('providedCoreLibsDir')
def providedModuleLibsDir = rootProject.property('providedModuleLibsDir')

dependencies {
    compileOnly(project(':'))
    if (file(providedCoreLibsDir).directory) {
        compileOnly fileTree(dir: providedCoreLibsDir,
                includes: ['**/jspecify-*.jar', '**/languagetool-core-*.jar', '**/commons-io-*.jar'])
        implementation fileTree(dir: providedModuleLibsDir, includes: ['**/language-zh-*.jar', '**/hanlp-portable-*.jar'])
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.languagetool.core)
        implementation(libs.languagetool.zh) {
            exclude module: 'languagetool-core'
        }
    }
    testImplementation(libs.junit4)
    testImplementation(libs.assertj.core)
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.languagetool.core)
    testImplementation(libs.commons.io)
}
