parameters:
  - name: testType
    default: 'GIT'
  - name: duration
    default: 600

steps:
  - task: Cache@2
    displayName: 'Cache Gradle'
    inputs:
      key: 'gradle | $(Agent.OS) | $(Build.SourcesDirectory)/build.gradle'
      path: '$(GRADLE_USER_HOME)'
  - script: |
      echo "Run ${{ parameters.testType }} integration test"
  - task: DockerCompose@0
    inputs:
      action: Run a Docker Compose command
      containerregistrytype: Container Registry
      dockerComposeFile: compose.yml
      dockerComposeCommand: up
      buildImages: true
      abortOnContainerExit: true
    env:
      DURATION: ${{ parameters.duration }}
      TYPE: ${{ parameters.testType }}
    displayName: 'Execute Integration-Test'
  - task: DockerCompose@0
    inputs:
      action: Run a Docker Compose command
      containerregistrytype: Container Registry
      dockerComposeFile: compose.yml
      dockerComposeCommand: down
