steps:
  - task: Bash@3
    displayName: 📂 SCP upload to sourceforge file management
    inputs:
      targetType: 'inline'
      script: |
        echo "Push manuals to sourceforge project web"
        srcdir=$(system.defaultworkingdirectory)/build/docs/manual/
        dest=$(SOURCEFORGE_FILE_USER)@frs.sourceforge.net
        destdir=/home/project-web/omegat/htdocs/manual-snapshot/
        echo "mkdir $destdir" | SSHPASS=$(SOURCEFORGE_FILE_PASS) sshpass -e sftp -v $dest || true
        SSHPASS=$(SOURCEFORGE_FILE_PASS) sshpass -e scp -v -r -oStrictHostKeyChecking=no $srcdir/* $dest:$destdir
