parameters:
  condition: false
  omegatVersion: "6.1.0"

steps:
  - task: Bash@3
    displayName: 📂 SCP upload to sourceforge file management
    condition: ${{ parameters.condition }}
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -q -y lftp
        echo "Push manuals to sourceforge project web"
        srcdir=$(system.defaultworkingdirectory)/build/docs/manual/
        dest=sftp://$(SOURCEFORGE_CI_USER)@frs.sourceforge.net
        destdir=/home/project-web/omegat/htdocs/manual/${{ parameters.omegatVersion }}-snapshot/
        target=/home/project-web/omegat/htdocs/manual-snapshot
        cmd="mkdir -p $destdir ; lcd $(system.defaultworkingdirectory)/build/docs/manual/ ; cd $destdir ; mirror --parallel=4 -Rev ; rm $target ; ln -s $destdir $target ; bye"
        env LFTP_PASSWORD=$(SOURCEFORGE_CI_PASS) lftp -oStrictHostKeyChecking=no --env-password -e "$cmd" $dest
