parameters:
  - name: omegatVersion
    default: ''

steps:
  - task: DownloadSecureFile@1
    name: sshKey
    displayName: "Download SSH private key"
    inputs:
      secureFile: omegat-ci-rsa
  - task: Bash@3
    displayName: Configure SSH to scan host key and store private key
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H "$SF_HOST" >> ~/.ssh/known_hosts 2>/dev/null
        cp $(Agent.TempDirectory)/omegat-ci-rsa ~/.ssh/id_rsa
        chmod 600 ~/.ssh/known_hosts ~/.ssh/id_rsa
        ssh-keygen -p -P "$(KEY_PASSWORD)" -N "" -f ~/.ssh/id_rsa
    env:
      SF_HOST: frs.sourceforge.net
      KEY_PASSWORD: $(SOURCEFORGE_CI_PASS)
  - task: Bash@3
    displayName: 📂upload to sourceforge file management via SFTP
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y lftp
        echo "Push OmegaT files to SourceForge file manager"
        srcdir=$(Pipeline.Workspace)/build/distributions/
        ls -l $srcdir/*
        dest=sftp://$(SOURCEFORGE_CI_USER)@$SF_HOST
        destdir=/home/frs/project/omegat/Weekly
        cmd="set net:max-retries 5; mkdir -p '$destdir'; lcd $srcdir; cd '$destdir'; mirror -R --verbose=3; bye"
        lftp -e "$cmd" $dest"
    env:
      OMEGAT_VERSION: ${{ parameters.omegatVersion }}
      SF_HOST: frs.sourceforge.net
