plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = rootProject.property('providedCoreLibsDir')
def providedModuleLibsDir = rootProject.property('providedModuleLibsDir')

dependencies {
    compileOnly(project(':'))
    if (file(providedModuleLibsDir).directory) {
        compileOnly fileTree(dir: providedCoreLibsDir, includes: ['**/jspecify-*.jar'])
        implementation fileTree(dir: providedModuleLibsDir, includes: ['**/flatlaf*'])
    } else {
        // platform independent dark theme
        implementation(libs.flatlaf)
        compileOnly(libs.jspecify)
    }
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.commons.io)
}
