#!/bin/bash
set -e
TARGET=$(dirname -- "${!#}")
env HOME=/home/xclient WINEPREFIX=/home/xclient/.wine WINEARCH=win32 iscc "$@"
# Find and chmod files generated by iscc
find /work/${TARGET}/ -type f -user "$(whoami)" -exec chmod 777 {} \;
