#!/usr/bin/env bash

relpaths() {
    for arg in "$@"; do printf -- "%s\n" "${arg#$PWD/}"; done
}

bindpaths() {
    for arg in $(relpaths "$@"); do
        if [ -e "$arg" ] && [[ "$arg" == /* ]]; then
            printf -- "-v %s:%s" "$arg" "$arg"
        fi
    done
}

if type nerdctl &> /dev/null ; then
    CMD=nerdctl
elif type docker &> /dev/null ; then
    CMD=docker
else
  echo Please install docker or nerdctl!
  exit 2
fi

# workaround for build failure on CI env.
# see https://sourceforge.net/p/omegat/bugs/1228/
PUID=`id -u`
PGID=`id -g`
IMAGE=omegatorg/innosetup:innosetup6
CONTEXT=`mktemp -d`

cat << __EOF__  > /$CONTEXT/Dockerfile
FROM docker.io/amake/innosetup:innosetup6-buster
USER root
RUN usermod -u $PUID -o xclient && groupmod -g $PGID -o xusers
RUN chown -R $PUID:$PGID /home/xclient /work
USER xclient
ENV HOME /home/xclient
ENV WINEPREFIX /home/xclient/.wine
ENV WINEARCH win32
WORKDIR /work
ENTRYPOINT ["iscc"]
__EOF__

$CMD build -t $IMAGE $CONTEXT
exec $CMD run -i --rm  \
   -u `id -u`:`id -g` \
   -v "$PWD":/work \
   $(bindpaths "$@") \
   $IMAGE \
   $(relpaths "$@")
