#!/usr/bin/env bash

relpaths() {
    for arg in "$@"; do printf -- "%s\n" "${arg#$PWD/}"; done
}

bindpaths() {
    for arg in $(relpaths "$@"); do
        if [ -e "$arg" ] && [[ "$arg" == /* ]]; then
            printf -- "-v %s:%s" "$arg" "$arg"
        fi
    done
}

if type nerdctl &> /dev/null ; then
    CMD=nerdctl
elif type docker &> /dev/null ; then
    CMD=docker
else
  echo Please install docker or nerdctl!
  exit 2
fi

exec $CMD run --rm -i \
    -v "$PWD":/work $(bindpaths "$@") \
    --entrypoint osslsigncode \
    amake/innosetup:innosetup6 \
    $(relpaths "$@")
