#!/usr/bin/env python3
# ##########################################################################
#  OmegaT - Computer Assisted Translation (CAT) tool
#           with fuzzy matching, translation memory, keyword search,
#           glossaries, and translation leveraging into updated projects.
#
#  Copyright (C) 2026 Stephan Pakebusch
#                Home page: https://www.omegat.org/
#                Support center: https://omegat.org/support
#
#  This file is part of OmegaT.
#
#  OmegaT is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  OmegaT is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ##########################################################################
"""Generates the team sync SVG diagrams in this directory.

Run from this directory:  python3 generate_team_sync_diagrams.py

The diagrams document the team project synchronization architecture
(org.omegat.core.team2), the autosave sync flow, the failure chain that
motivated the sync robustness changes, and the repository/project layout
migration from OmegaT 3.x-era projects to the current team layout.
"""

import os

W, H = 1280, 720
DARK = "#1e282c"
GRAY = "#6F868C"
RED = "#ef3b39"
ORANGE = "#F89838"
LIGHT = "#D4E6EB"
PALE = "#F4F9FB"
GREEN = "#3d8b40"

GPL_COMMENT = """<!--
  OmegaT - Computer Assisted Translation (CAT) tool
           with fuzzy matching, translation memory, keyword search,
           glossaries, and translation leveraging into updated projects.

  Copyright (C) 2026 Stephan Pakebusch
                Home page: https://www.omegat.org/
                Support center: https://omegat.org/support

  This file is part of OmegaT.

  OmegaT is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  OmegaT is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <https://www.gnu.org/licenses/>.

  Generated by generate_team_sync_diagrams.py - edit the generator, not
  this file.
-->
"""

DEFS = f"""<defs>
  <marker id="arr" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7"
          orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{DARK}"/></marker>
  <marker id="arr-red" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7"
          orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{RED}"/></marker>
  <marker id="arr-gray" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7"
          orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{GRAY}"/></marker>
  <marker id="arr-green" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7"
          orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="{GREEN}"/></marker>
</defs>
"""

LOGO_DEFS = """<defs>
  <filter id="OMEGA_SHADOW" x="0" y="0" width="2" height="2">
    <feGaussianBlur in="SourceAlpha" stdDeviation="5"/>
    <feOffset dx="10" dy="10"/>
    <feComponentTransfer><feFuncA type="linear" slope="0.2"/></feComponentTransfer>
    <feMerge><feMergeNode/><feMergeNode in="SourceGraphic"/></feMerge>
  </filter>
  <linearGradient id="OMEGA_GRAD" gradientUnits="userSpaceOnUse" x1="127.8472" y1="271.71091" x2="127.8472" y2="32.0532" gradientTransform="translate(17.999819,2.62897)">
    <stop offset="0.0053" style="stop-color:#6F868C"/><stop offset="0.0165" style="stop-color:#72888F"/>
    <stop offset="0.1363" style="stop-color:#8CA0A6"/><stop offset="0.2648" style="stop-color:#A4B6BC"/>
    <stop offset="0.4031" style="stop-color:#B7C9CF"/><stop offset="0.5558" style="stop-color:#C7DADF"/>
    <stop offset="0.7342" style="stop-color:#D1E3E8"/><stop offset="1" style="stop-color:#D4E6EB"/>
  </linearGradient>
  <linearGradient id="T_GRAD" gradientUnits="userSpaceOnUse" x1="189.86819" y1="187.1973" x2="229.1293" y2="2.4877999">
    <stop offset="0.0053" style="stop-color:#F89838"/><stop offset="0.206" style="stop-color:#F6B236"/>
    <stop offset="0.4384" style="stop-color:#F6CA32"/><stop offset="0.6554" style="stop-color:#F7DB2B"/>
    <stop offset="0.8491" style="stop-color:#F7E628"/><stop offset="1" style="stop-color:#F7EC25"/>
  </linearGradient>
  <g id="OMEGAT_LOGO">
    <rect x="65.106812" y="77.532959" width="226.95799" height="226.95799" style="fill:#f7f9f9;stroke:#000000;stroke-width:4"/>
    <path style="fill:url(#OMEGA_GRAD);filter:url(#OMEGA_SHADOW)" d="m 25.658819,143.89497 c 0,41.372 28.660999,70.73 54.890999,88.936 -7.585999,0 -20.790999,0 -20.790999,0 -16.153,0 -20.249,-0.706 -27.689001,-19.266 -0.303999,-0.759 -1.038999,-1.256 -1.855999,-1.256 l -10.214,0 c -0.567,0 -1.108,0.241 -1.487,0.663 -0.379,0.422 -0.562,0.985 -0.501,1.55 l 6.201,58.031 c 0.109,1.017 0.966,1.787 1.989,1.787 l 93.383001,0 c 0.708,0 1.364,-0.375 1.724,-0.985 l 2.917,-4.955 c 0.368,-0.624 0.369,-1.398 0.003,-2.024 l -0.506,-0.864 c -14.385,-24.598 -41.163001,-70.384 -40.804002,-119.125 0,-29.854 5.41,-53.143 16.081001,-69.235 10.699001,-16.135 26.338001,-24.316 46.483001,-24.316 20.274,0 36.027,7.953 46.821,23.637 10.688,15.531 16.107,37.858 16.107,66.362 0,51.946 -29.167,101.864 -41.622,123.18 l -0.417,0.714 c -0.397,0.68 -0.358,1.529 0.099,2.17 l 3.283,4.604 c 0.375,0.526 0.981,0.839 1.628,0.839 l 91.923,0 c 0.994,0 1.837,-0.73 1.979,-1.714 l 8.391,-58.031 c 0.083,-0.574 -0.088,-1.156 -0.468,-1.596 -0.38,-0.438 -0.932,-0.69 -1.512,-0.69 l -10.216,0 c -0.806,0 -1.532,0.483 -1.844,1.226 -7.783,18.531 -11.865,19.296 -26.243,19.296 0,0 -17.382,0 -24.938,0 23.381,-18.69 56.85,-46.58 56.85,-90.352 0,-63.469 -49.123,-107.797 -119.458,-107.797 -70.764002,-0.002 -120.187002,44.908 -120.187002,109.211 z"/>
    <path style="fill:#1e282c" d="m 145.84482,32.68197 c -17.435,0 -33.882,2.683 -48.883002,7.973 -14.783,5.214 -27.816,12.832 -38.737,22.641 -11.013,9.892 -19.58,21.744 -25.462,35.229 -6.042,13.851 -9.105,29.115 -9.105,45.37 0,21.473 7.679,41.858 22.823,60.588 7.582,9.379 16.92,18.207 27.854,26.347 l -14.577,0 c -8.347,0 -12.896,-0.369 -16.173,-2.465 -3.317,-2.122 -6.026,-6.481 -9.66,-15.545 -0.609,-1.518 -2.079,-2.511 -3.713,-2.511 l -10.212,0 c -1.135,0 -2.216,0.481 -2.975,1.325 -0.759,0.845 -1.123,1.972 -1.002,3.1 l 6.201,58.031 c 0.217,2.032 1.932,3.574 3.977,3.574 l 93.382002,0 c 1.417,0 2.728,-0.75 3.447,-1.971 l 2.917,-4.955 c 0.735,-1.248 0.737,-2.797 0.006,-4.048 l -0.507,-0.867 c -6.861,-11.732 -17.231,-29.463 -25.685002,-50.082 -4.62,-11.265 -8.205,-22.288 -10.656,-32.763 -2.861,-12.226 -4.27,-24.086 -4.188,-35.254 0,-0.009 0,-0.019 0,-0.029 0,-14.669 1.357,-27.923 4.033,-39.395 2.639,-11.314 6.581,-20.977 11.715002,-28.719 10.305,-15.542 25.384,-23.422 44.816,-23.422 19.577,0 34.775,7.661 45.174,22.771 5.137,7.465 9.082,16.756 11.725,27.616 2.674,10.988 4.03,23.643 4.03,37.612 0,22.021 -5.354,46.297 -15.911,72.155 -8.788,21.52 -19.212,39.359 -25.44,50.018 l -0.416,0.712 c -0.794,1.36 -0.717,3.06 0.197,4.342 l 3.283,4.603 c 0.751,1.052 1.964,1.677 3.257,1.677 l 91.923,0 c 1.988,0 3.674,-1.46 3.959,-3.428 l 8.392,-58.031 c 0.166,-1.147 -0.175,-2.313 -0.936,-3.189 -0.76,-0.878 -1.862,-1.382 -3.023,-1.382 l -10.216,0 c -1.611,0 -3.064,0.966 -3.688,2.45 -3.762,8.958 -6.614,13.492 -9.842,15.649 -3.081,2.059 -7.149,2.421 -14.558,2.421 l -19.256,0 c 10.409,-8.448 22.111,-18.599 31.947,-31.103 6.544,-8.32 11.629,-16.954 15.112,-25.663 4.054,-10.133 6.108,-20.76 6.108,-31.585 0,-15.938 -3.008,-30.927 -8.938,-44.549 -5.799,-13.318 -14.252,-25.029 -25.125,-34.809 -10.83,-9.742 -23.774,-17.308 -38.474,-22.488 -14.97,-5.275 -31.429,-7.951 -48.92,-7.951 l 0,0 z m -118.187002,111.213 c 0,-64.045 49.244001,-107.213 118.187002,-107.213 69.307,0 117.458,43.168 117.458,105.797 l 0,0 0,0 c 0,45.646 -37.572,73.952 -60.553,92.351 l 4,0 0,0 2.41,0 0,0 24.23,0 c 15.321,0 20.063,-1.414 28.088,-20.521 l 10.216,0 0,0 0,0 -8.392,58.03 -91.922,0 -3.283,-4.603 0,0 0,0 c 12.402,-21.231 42.313,-71.829 42.313,-124.903 0,-57.323 -22.25,-91.999 -64.929,-91.999 -42.315,0 -64.564001,35.385 -64.564001,95.536 -0.002,0.292 -0.003,0.584 -0.003,0.877 -0.035,49.569 27.808001,96.569 41.586001,120.137 l 0,0 0,0 -2.917,4.955 -93.382001,0 -6.201001,-58.029 0,0 0,0 10.212001,0 c 7.660999,19.106 12.404999,20.521 29.545999,20.521 l 20.159,0 0,0 3.202001,0 0,0 4,0 c -20.793001,-13.446 -59.461001,-43.876 -59.461001,-90.936 l 0,0 0,0 z"/>
    <g transform="translate(17.999819,2.62897)">
      <path style="opacity:0.75" d="m 213.799,0.835 c -2.431,0 -6.061,0.811 -9.55,4.678 0,0 0.001,-0.001 0.002,-0.001 -12.968,14.276 -41.592,38.801 -52.015,43.395 l -0.067,0.029 -0.066,0.032 c -4.885,2.37 -9.878,5.65 -9.878,12.002 0,2.827 1.132,5.242 3.185,6.801 1.667,1.265 3.807,1.906 6.361,1.906 l 15.028,0 -0.316,40.34 0,0.015 0,0.016 c 0,6.482 -0.182,16.369 -0.356,25.93 -0.173,9.441 -0.336,18.357 -0.336,24.157 0,8.939 4.283,17.845 11.75,24.43 3.834,3.38 8.338,6.031 13.389,7.878 5.359,1.96 11.189,2.954 17.326,2.954 19.707,0 37.266,-4.894 50.775,-14.149 l 0.046,-0.032 0.046,-0.032 c 3.351,-2.438 4.382,-6.308 2.564,-9.492 l -2.351,-4.887 -0.024,-0.054 -0.027,-0.052 c -1.671,-3.229 -3.932,-3.908 -5.533,-3.908 -1.076,0 -2.141,0.321 -3.168,0.952 -4.635,2.506 -9.133,3.484 -15.994,3.484 -3.84,0 -7.019,-1.641 -9.449,-4.874 -1.67,-2.224 -2.989,-5.201 -3.924,-8.853 -1.118,-4.365 -1.684,-9.711 -1.684,-15.889 l 0,-26.556 c 0,-14.072 0,-28.579 0.517,-41.378 l 36.72,0 c 1.664,0 5.678,-0.555 6.991,-5.7 l 0.009,-0.028 0.007,-0.029 3.387,-14.113 c 0.671,-1.711 0.509,-3.624 -0.467,-5.223 -1.175,-1.926 -3.331,-3.076 -5.768,-3.076 l -39.853,0 1.225,-31.475 0.003,-0.078 0,-0.078 c -0.001,-5.324 -3.498,-9.042 -8.505,-9.042 l 0,0 z M 146.225,60.97 c 0,-3.361 2.078,-5.712 7.624,-8.403 11.438,-5.04 40.544,-30.252 53.366,-44.37 2.426,-2.69 4.853,-3.362 6.584,-3.362 3.117,0 4.504,2.354 4.504,5.042 l 0,0 0,0 -1.387,35.631 4,0 0,0 0.003,0 0,0 40.009,0 c 1.64,0 2.633,1.046 2.639,2.148 0.002,0.294 -0.066,0.593 -0.212,0.876 l -3.47,14.455 c -0.344,1.346 -1.038,2.69 -3.116,2.69 l -40.543,0 c -0.683,13.567 -0.693,29.414 -0.693,44.653 0,0.242 0,0.483 0,0.725 l 0,26.556 c 0,27.564 10.742,33.616 19.057,33.616 7.279,0 12.479,-1.008 18.021,-4.033 0.38,-0.246 0.76,-0.403 1.141,-0.403 0.659,0 1.319,0.468 1.98,1.746 l 2.424,5.041 c 0.292,0.474 0.42,0.946 0.422,1.404 0.006,1.17 -0.812,2.241 -1.809,2.966 -5.892,4.037 -21.483,13.449 -48.514,13.449 -23.564,0 -38.465,-15.799 -38.465,-31.262 l 0,0 0,0 c 0,-11.767 0.692,-37.313 0.692,-50.087 l 0.316,-40.371 0,0 0,0 0,0 0.031,-4 -19.06,0 c -3.118,0 -5.544,-1.344 -5.544,-4.707 l 0,0 0,0 z"/>
      <path style="fill:url(#T_GRAD)" d="m 208.565,4.022 0.005,-0.005 c -13.372,14.725 -41.87,39.116 -52.692,43.885 -4.611,2.235 -8.817,4.998 -8.817,10.233 0,4.137 2.891,6.707 7.545,6.707 0,0 13.82,0 17.044,0 -0.029,3.673 -0.332,42.355 -0.332,42.355 0,6.515 -0.182,16.412 -0.356,25.982 -0.173,9.431 -0.336,18.338 -0.336,24.118 l 0,0.001 c 0,15.996 15.471,33.262 40.466,33.262 19.303,0 36.47,-4.771 49.645,-13.8 2.63,-1.911 3.397,-4.74 1.956,-7.07 l 0.102,0.186 -2.424,-5.041 c -0.812,-1.572 -1.76,-2.461 -2.924,-2.77 -1.01,-0.268 -2.05,-0.06 -3.089,0.614 l 0.131,-0.078 c -4.995,2.727 -9.779,3.789 -17.063,3.789 -11,0 -17.058,-11.228 -17.058,-31.615 l 0,-26.555 c 0,-14.82 0.018,-30.067 0.621,-43.378 3.495,0 38.616,0 38.616,0 1.816,0 4.168,-0.728 5.054,-4.195 l 3.476,-14.483 -0.166,0.448 c 0.29,-0.564 0.435,-1.173 0.435,-1.781 0,-0.705 -0.194,-1.409 -0.579,-2.04 -0.809,-1.326 -2.326,-2.118 -4.059,-2.119 0,0 -38.158,0 -41.934,0 0.144,-3.685 1.306,-33.556 1.306,-33.557 0,-4.288 -2.613,-7.116 -6.502,-7.116 -2.028,0.001 -5.073,0.699 -8.071,4.023 z"/>
      <path style="fill:#ef3b39" d="m 216.634,-2 c -2.431,0 -6.061,0.811 -9.55,4.678 0,0 0.001,-10e-4 0.002,-10e-4 -12.968,14.276 -41.592,38.801 -52.015,43.395 l -0.067,0.029 -0.066,0.032 c -4.885,2.37 -9.878,5.65 -9.878,12.002 0,2.827 1.132,5.242 3.185,6.801 1.667,1.265 3.807,1.906 6.361,1.906 l 15.028,0 -0.316,40.34 0,0.015 0,0.016 c 0,6.482 -0.182,16.369 -0.356,25.93 -0.173,9.441 -0.336,18.357 -0.336,24.156 0,8.939 4.283,17.845 11.75,24.43 3.834,3.38 8.338,6.031 13.389,7.878 5.359,1.96 11.189,2.954 17.326,2.954 19.707,0 37.266,-4.894 50.775,-14.149 l 0.046,-0.032 0.046,-0.032 c 3.351,-2.438 4.382,-6.308 2.564,-9.492 l -2.351,-4.887 -0.024,-0.054 -0.027,-0.052 c -1.671,-3.229 -3.932,-3.908 -5.533,-3.908 -1.076,0 -2.141,0.321 -3.168,0.952 -4.635,2.506 -9.133,3.484 -15.994,3.484 -3.84,0 -7.019,-1.641 -9.449,-4.874 -1.67,-2.224 -2.989,-5.201 -3.924,-8.852 -1.118,-4.365 -1.684,-9.711 -1.684,-15.889 l 0,-26.556 c 0,-14.072 0,-28.579 0.517,-41.378 l 36.72,0 c 1.664,0 5.678,-0.555 6.991,-5.7 l 0.009,-0.028 0.007,-0.029 3.387,-14.113 c 0.671,-1.711 0.509,-3.624 -0.467,-5.223 -1.175,-1.926 -3.331,-3.076 -5.768,-3.076 l -39.854,0 1.225,-31.475 0.003,-0.078 0,-0.078 C 225.138,1.718 221.641,-2 216.634,-2 l 0,0 z M 149.06,58.135 c 0,-3.361 2.078,-5.712 7.624,-8.403 11.438,-5.04 40.544,-30.252 53.366,-44.37 2.426,-2.69 4.852,-3.362 6.584,-3.362 3.117,0 4.504,2.354 4.504,5.042 l 0,0 0,0 -1.387,35.631 4,0 0,0 0.003,0 0,0 40.009,0 c 1.64,0 2.633,1.046 2.639,2.148 0.002,0.294 -0.066,0.593 -0.212,0.876 l -3.47,14.455 c -0.344,1.346 -1.038,2.69 -3.116,2.69 l -40.543,0 c -0.683,13.567 -0.693,29.414 -0.693,44.653 0,0.242 0,0.483 0,0.725 l 0,26.556 c 0,27.563 10.742,33.615 19.057,33.615 7.279,0 12.479,-1.008 18.021,-4.033 0.38,-0.246 0.76,-0.403 1.141,-0.403 0.659,0 1.319,0.468 1.98,1.746 l 2.424,5.041 c 0.292,0.474 0.42,0.946 0.422,1.404 0.006,1.17 -0.812,2.241 -1.809,2.966 -5.892,4.037 -21.483,13.449 -48.514,13.449 -23.564,0 -38.465,-15.799 -38.465,-31.262 l 0,0 0,0 c 0,-11.767 0.692,-37.313 0.692,-50.086 l 0.316,-40.371 0,0 0,0 0,0 0.031,-4 -19.06,0 c -3.118,0 -5.544,-1.344 -5.544,-4.707 l 0,0 0,0 z"/>
    </g>
  </g>
</defs>"""

FONT = "font-family='Helvetica, Arial, sans-serif'"


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def header(title, subtitle=""):
    out = [f"<text x='40' y='52' {FONT} font-size='30' font-weight='bold' fill='{DARK}'>{esc(title)}</text>"]
    if subtitle:
        out.append(f"<text x='40' y='80' {FONT} font-size='16' fill='{GRAY}'>{esc(subtitle)}</text>")
    return "\n".join(out)


def box(x, y, w, h, title, lines, fill=PALE, stroke=DARK, title_fill=None, mono_lines=True, fs=13):
    title_fill = title_fill or DARK
    out = [f"<rect x='{x}' y='{y}' width='{w}' height='{h}' rx='8' fill='{fill}' stroke='{stroke}' stroke-width='1.5'/>"]
    out.append(f"<text x='{x + w / 2}' y='{y + 24}' {FONT} font-size='15' font-weight='bold' "
               f"text-anchor='middle' fill='{title_fill}'>{esc(title)}</text>")
    if lines:
        out.append(f"<line x1='{x + 10}' y1='{y + 34}' x2='{x + w - 10}' y2='{y + 34}' stroke='{stroke}' stroke-width='0.7'/>")
    font = "font-family='Menlo, Consolas, monospace'" if mono_lines else FONT
    for i, line in enumerate(lines):
        color = DARK
        weight = ""
        if line.startswith("!"):
            line, color, weight = line[1:], RED, " font-weight='bold'"
        elif line.startswith("+"):
            line, color, weight = line[1:], GREEN, " font-weight='bold'"
        elif line.startswith("~"):
            line, color = line[1:], GRAY
        out.append(f"<text x='{x + 14}' y='{y + 54 + i * 19}' {font} font-size='{fs}'{weight} "
                   f"fill='{color}'>{esc(line)}</text>")
    return "\n".join(out)


def arrow(x1, y1, x2, y2, label="", color=DARK, dashed=False, marker="arr", label_dy=-6, label_fs=13):
    dash = " stroke-dasharray='7,5'" if dashed else ""
    out = [f"<line x1='{x1}' y1='{y1}' x2='{x2}' y2='{y2}' stroke='{color}' stroke-width='1.8'{dash} "
           f"marker-end='url(#{marker})'/>"]
    if label:
        mx, my = (x1 + x2) / 2, (y1 + y2) / 2
        out.append(f"<text x='{mx}' y='{my + label_dy}' {FONT} font-size='{label_fs}' text-anchor='middle' "
                   f"fill='{color}'>{esc(label)}</text>")
    return "\n".join(out)


def badge(x, y, n, color=RED):
    return (f"<circle cx='{x}' cy='{y}' r='13' fill='{color}'/>"
            f"<text x='{x}' y='{y + 5}' {FONT} font-size='15' font-weight='bold' text-anchor='middle' "
            f"fill='white'>{n}</text>")


def logo_use(x, y, size):
    k = size / 308.0
    return f"<use href='#OMEGAT_LOGO' transform='translate({x},{y}) scale({k:.4f})'/>"


def footer():
    """Two-line plain-words version of the project GPL file header."""
    line1 = ("OmegaT - Computer Assisted Translation (CAT) tool, with fuzzy matching, "
             "translation memory, keyword search, glossaries, and translation leveraging "
             "into updated projects.")
    line2 = ("Free software under the GNU GPL v3 or later: run it for any purpose, study and "
             "modify it, share copies and your changes - distributed WITHOUT ANY WARRANTY - "
             "https://www.omegat.org/")
    return "\n".join([
        f"<line x1='40' y1='688' x2='{W - 40}' y2='688' stroke='{LIGHT}' stroke-width='1'/>",
        logo_use(40, 692, 24),
        f"<text x='74' y='702' {FONT} font-size='11' fill='{GRAY}'>{esc(line1)}</text>",
        f"<text x='74' y='716' {FONT} font-size='11' fill='{GRAY}'>{esc(line2)}</text>",
    ])


def legend_fixes(x, y):
    items = [
        ("1", "fix: prepared commit info keeps path and versions"),
        ("2", "fix: repository init failures fail fast, localized"),
        ("3", "feat: version checkout errors name file/version/repo"),
        ("4", "feat: stale base marker recovers via empty-base merge"),
    ]
    out = [f"<text x='{x}' y='{y}' {FONT} font-size='14' font-weight='bold' fill='{DARK}'>Changes in this series</text>"]
    for i, (n, t) in enumerate(items):
        yy = y + 20 + i * 24
        out.append(badge(x + 12, yy - 5, n))
        out.append(f"<text x='{x + 34}' y='{yy}' {FONT} font-size='13' fill='{DARK}'>{esc(t)}</text>")
    return "\n".join(out)


def svg(title, body):
    return (f"<?xml version='1.0' encoding='UTF-8'?>\n{GPL_COMMENT}"
            f"<svg xmlns='http://www.w3.org/2000/svg' width='{W}' height='{H}' viewBox='0 0 {W} {H}'>\n"
            f"<title>{esc(title)}</title>\n{DEFS}{LOGO_DEFS}"
            f"<rect width='{W}' height='{H}' fill='white'/>\n{body}\n</svg>\n")


def write(name, title, body):
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(svg(title, body))
    print("wrote", path)


# ---------------------------------------------------------------- page 1
def page_architecture():
    b = [header("Team project synchronization - classes and hook points",
                "org.omegat.core.team2 - class relations, responsibilities, and where the sync robustness series intervenes")]

    b.append(box(40, 110, 300, 170, "RealProject", [
        "loadProject()",
        "saveProject()",
        "teamSyncPrepare()  [autosave]",
        "teamSync()         [autosave]",
        "rebaseAndCommitProject()",
        "~fields: tmxPrepared,",
        "~        glossaryPrepared",
    ]))

    b.append(box(440, 110, 330, 170, "RebaseAndCommit (static)", [
        "prepare(provider, dir, path)",
        "rebaseAndCommit(prep, ...)",
        "commitPrepared(prep, ...)",
        "~VERSION_PREFIX =",
        "~ \"version-based-on.\"",
    ]))
    b.append(badge(755, 125, "1"))
    b.append(badge(755, 155, "4"))

    b.append(box(870, 110, 370, 170, "PreparedFileInfo", [
        "path, versionBase, versionHead",
        "fileBase, fileHead  (temp copies)",
        "needToCommit, commitComment,",
        "charset",
        "~immutable carrier between the",
        "~prepare, rebase and commit steps",
    ]))

    b.append(box(440, 340, 330, 190, "RemoteRepositoryProvider", [
        "initializeRepositories()",
        "switchToVersion(path, version)",
        "copyFilesFromReposToProject()",
        "copyFilesFromProjectToRepos()",
        "commitFileAfterVersion()",
        "oneMapping(path) / Mapping",
    ]))
    b.append(badge(755, 355, "2"))
    b.append(badge(755, 385, "3"))

    b.append(box(40, 340, 300, 190, "ProjectTeamSettings", [
        ".repositories/settings.properties",
        "get/set(key, value)",
        "~key: version-based-on.<path>",
        "~     = last synchronized base",
        "~       version of that file",
        "!survives re-clones of the",
        "!cached repository copies",
    ]))

    b.append(box(870, 340, 370, 100, "IRemoteRepository2", [
        "switchToVersion(version)",
        "commit(onVersions, comment)",
        "getFileVersion(file)",
    ]))
    b.append(box(870, 470, 370, 60, "GITRemoteRepository2 - SVNRemoteRepository2 - FileRepository - HTTPRemoteRepository", [], fs=12))

    b.append(arrow(340, 195, 440, 195, "prepare / rebase / commit"))
    b.append(arrow(770, 180, 870, 180, "returns"))
    b.append(arrow(605, 280, 605, 340, "checkout, copy, commit"))
    b.append(arrow(440, 430, 340, 430, "reads/writes sync markers"))
    b.append(arrow(770, 430, 870, 400, "delegates to backend"))
    b.append(arrow(1055, 440, 1055, 470, "", GRAY, dashed=True, marker="arr-gray"))
    b.append(arrow(190, 280, 190, 340, "", GRAY, dashed=True, marker="arr-gray"))

    b.append(legend_fixes(40, 590))
    b.append(f"<text x='870' y='590' {FONT} font-size='13' fill='{GRAY}'>The project folder keeps a private clone per"
             f"</text><text x='870' y='608' {FONT} font-size='13' fill='{GRAY}'>repository under .repositories/&lt;url&gt;;"
             f"</text><text x='870' y='626' {FONT} font-size='13' fill='{GRAY}'>settings.properties lives beside the clones.</text>")
    b.append(footer())
    write("01-team-sync-architecture.svg", "Team sync architecture", "\n".join(b))


# ---------------------------------------------------------------- page 2
def page_flow():
    b = [header("Autosave team sync - the prepare/rebase/commit flow",
                "SaveThread runs the three phases; the middle one holds the edit lock, the outer ones do not")]

    b.append(box(40, 110, 380, 150, "1 - teamSyncPrepare()", [
        "for project_save.tmx + glossary:",
        "  read marker (settings.properties)",
        "  checkout BASE = marker version",
        "  checkout HEAD = latest",
        "  copy both to .repositories/prep/",
    ]))
    b.append(badge(400, 125, "4"))

    b.append(box(450, 110, 380, 150, "2 - teamSync()  [locked]", [
        "save project TMX",
        "rebaseAndCommit(prep, ...):",
        "  compare BASE vs local vs HEAD",
        "  merge if both sides changed",
        "  returns PreparedFileInfo",
    ]))
    b.append(badge(810, 125, "1"))

    b.append(box(860, 110, 380, 150, "3 - commitPrepared()  [async]", [
        "copy file into the cached clone",
        "commit on top of head version",
        "push / upload",
        "update marker to new version",
    ]))

    b.append(arrow(420, 185, 450, 185))
    b.append(arrow(830, 185, 860, 185))

    b.append(box(40, 330, 570, 210, "rebaseAndCommit() outcome matrix", [
        "local changed   remote changed   action",
        "no              no               reload, nothing to do",
        "yes             no               commit local file",
        "no              yes              take remote file (backup first)",
        "yes             yes              rebase local onto HEAD, commit merge",
        "~BASE for the comparison = marker version; a provably lost marker",
        "~now merges against an empty base and heals itself (was: load failed)",
    ]))
    b.append(badge(590, 345, "4"))

    b.append(box(660, 330, 580, 210, "What broke in the field (before this series)", [
        "!teamSync returned a PreparedFileInfo without path/versions",
        "!  -> commitPrepared(null path) -> NPE on EVERY autosave commit",
        "!  -> only manual synchronous saves reached the repository",
        "~The rebase itself succeeded; the loss happened in the handover",
        "~between phase 2 and phase 3.",
        "+Fixed: the returned info now carries path, base and head version.",
    ]))
    b.append(badge(1220, 345, "1"))

    b.append(legend_fixes(40, 590))
    b.append(footer())
    write("02-team-sync-flow.svg", "Autosave team sync flow", "\n".join(b))


# ---------------------------------------------------------------- page 3
def page_failure_chain():
    b = [header("Field incident - three cryptic errors, one afternoon",
                "Observed while opening a 3.x-era project with OmegaT 6.2; arrows show cause -> effect, green shows the new behaviour")]

    y1 = 120
    b.append(box(40, y1, 360, 120, "Chain A - stale sync marker", [
        "settings.properties points at a",
        "commit that a fresh clone of the",
        "repository does not contain",
    ]))
    b.append(arrow(400, y1 + 60, 460, y1 + 60, "checkout", RED, marker="arr-red"))
    b.append(box(460, y1, 360, 120, "JGit MissingObjectException", [
        "!\"Missing unknown <hash>\"",
        "surfaced raw in the load-error",
        "dialog; project unloadable",
    ]))
    b.append(arrow(820, y1 + 60, 880, y1 + 60, "now", GREEN, marker="arr-green"))
    b.append(box(880, y1, 360, 120, "Fixes 3 + 4", [
        "+message names file, version,",
        "+repository and the purpose; load",
        "+recovers via empty-base merge",
    ], stroke=GREEN))

    y2 = 280
    b.append(box(40, y2, 360, 120, "Chain B - swallowed init failure", [
        "config.lock left behind while the",
        "previous project instance closes;",
        "GIT init throws LockFailedException",
    ]))
    b.append(arrow(400, y2 + 60, 460, y2 + 60, "Log + break", RED, marker="arr-red"))
    b.append(box(460, y2, 360, 120, "Lists out of sync", [
        "repositories empty, definitions not;",
        "!next access: \"Index 0 out of",
        "!bounds for length 0\"",
    ]))
    b.append(arrow(820, y2 + 60, 880, y2 + 60, "now", GREEN, marker="arr-green"))
    b.append(box(880, y2, 360, 120, "Fix 2", [
        "+init failure aborts the provider",
        "+with the repository URL and the",
        "+original cause in the message",
    ], stroke=GREEN))

    y3 = 440
    b.append(box(40, y3, 360, 120, "Chain C - lost prepared path", [
        "async save handover object built",
        "with only 3 of 8 fields; path and",
        "head version stayed null",
    ]))
    b.append(arrow(400, y3 + 60, 460, y3 + 60, "commitPrepared", RED, marker="arr-red"))
    b.append(box(460, y3, 360, 120, "NPE on every autosave sync", [
        "!withLeadingSlash(null) ->",
        "!\"Fehler beim Speichern der",
        "!Projektdatei!\" repeatedly",
    ]))
    b.append(arrow(820, y3 + 60, 880, y3 + 60, "now", GREEN, marker="arr-green"))
    b.append(box(880, y3, 360, 120, "Fix 1", [
        "+PreparedFileInfo carries path,",
        "+base and head version through",
        "+the async commit",
    ], stroke=GREEN))

    b.append(f"<text x='40' y='625' {FONT} font-size='13' fill='{GRAY}'>Chains A and B happened in the old, 3.x-era project;"
             f" chain C affects every team project on the autosave route.</text>")
    b.append(footer())
    write("03-team-sync-failure-chain.svg", "Team sync failure chains", "\n".join(b))


# ---------------------------------------------------------------- page 4
def page_migration():
    b = [header("Repository layout migration - 3.x-era project vs. current team layout",
                "Why a converted project can carry stale state: the sync markers live outside the clones and survive their rebuild")]

    b.append(box(40, 120, 560, 250, "3.x-era project (old style)", [
        "myproject/",
        "  omegat.project      <- no <repositories> mapping",
        "  .git/               <- project folder IS the checkout",
        "  omegat/project_save.tmx",
        "  source/  target/  glossary/  tm/",
        "",
        "~sync = plain git pull/push of the project folder",
        "~server-side omegat.project often never converted",
    ]))

    b.append(box(680, 120, 560, 250, "current team layout (team2)", [
        "myproject/",
        "  omegat.project      <- <repositories> + mapping",
        "  .repositories/",
        "    <url-derived-dir>/   <- private cached clone",
        "    prep/                <- temp base/head copies",
        "!   settings.properties  <- sync markers",
        "  omegat/project_save.tmx",
        "  source/  target/  glossary/  tm/",
    ]))

    b.append(arrow(600, 245, 680, 245, "conversion (local only!)", RED, marker="arr-red"))

    b.append(box(40, 430, 1200, 150, "The migration trap", [
        "The conversion adds the repository mapping to the LOCAL omegat.project; the copy committed in the repository can stay old-style",
        "(\"There are no git settings in the remote project file\").  The cached clones under .repositories/ can be rebuilt at any time - a",
        "changed URL, a deleted folder, a rewritten history - but settings.properties stays, and its version-based-on.<path> markers then",
        "point at commits the fresh clone never had.  Before this series that aborted the project load with \"Missing unknown <hash>\";",
        "+now the load warns, merges local and remote as a three-way merge against an empty base and heals the marker.  Only provably",
        "+missing versions count as stale - transient failures (network, locks) still fail loudly and keep the marker.",
    ], fs=14))
    b.append(badge(1210, 445, "4"))

    b.append(legend_fixes(40, 588))
    b.append(footer())
    write("04-repository-migration.svg", "Repository layout migration", "\n".join(b))


if __name__ == "__main__":
    page_architecture()
    page_flow()
    page_failure_chain()
    page_migration()
