plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(libs.junit4)
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.addAll '-Xlint'
}

test {
    useJUnit()
    workingDir = rootProject.projectDir
}