/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2014 Briac Pilpre
               2015 Aaron Madlon-Kay
               2016 Aaron Madlon-Kay
               Home page: https://www.omegat.org/
               Support center: https://omegat.org/support

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
 **************************************************************************/

package org.omegat.gui.preferences.view;

import org.omegat.util.OStrings;

/**
 * @author Briac Pilpre
 * @author Aaron Madlon-Kay
 */
@SuppressWarnings("serial")
public class CustomColorSelectionPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomColorSelectionPanel
     */
    public CustomColorSelectionPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sampleEditorPane = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        searchLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchEastPanel = new javax.swing.JPanel();
        clearSearchButton = new javax.swing.JButton();
        matchCountLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        colorStylesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        resetCurrentColorButton = new javax.swing.JButton();
        colorChooser = new javax.swing.JColorChooser();

        sampleEditorPane.setEditable(false);
        sampleEditorPane.setText("Sample translation text");
        sampleEditorPane.setMinimumSize(new java.awt.Dimension(400, 100));
        sampleEditorPane.setName(""); // NOI18N
        sampleEditorPane.setPreferredSize(new java.awt.Dimension(400, 100));
        sampleEditorPane.setRequestFocusEnabled(false);

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tablePanel.setLayout(new java.awt.BorderLayout());

        searchPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 0));
        searchPanel.setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(searchLabel, OStrings.getString("GUI_COLORS_SEARCH_LABEL")); // NOI18N
        searchLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        searchPanel.add(searchLabel, java.awt.BorderLayout.WEST);
        searchPanel.add(searchTextField, java.awt.BorderLayout.CENTER);

        searchEastPanel.setLayout(new java.awt.BorderLayout());

        clearSearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/omegat/gui/resources/clear-button.png"))); // NOI18N
        clearSearchButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        clearSearchButton.setBorderPainted(false);
        clearSearchButton.setContentAreaFilled(false);
        clearSearchButton.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/org/omegat/gui/resources/clear-button-disabled.png"))); // NOI18N
        clearSearchButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/org/omegat/gui/resources/clear-button-pressed.png"))); // NOI18N
        searchEastPanel.add(clearSearchButton, java.awt.BorderLayout.WEST);

        matchCountLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 8, 0, 0));
        searchEastPanel.add(matchCountLabel, java.awt.BorderLayout.CENTER);

        searchPanel.add(searchEastPanel, java.awt.BorderLayout.EAST);

        tablePanel.add(searchPanel, java.awt.BorderLayout.NORTH);

        colorStylesTable.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(colorStylesTable);

        tablePanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(tablePanel, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(0, 1));

        org.openide.awt.Mnemonics.setLocalizedText(resetCurrentColorButton, OStrings.getString("GUI_COLORS_RESET_COLOR")); // NOI18N
        resetCurrentColorButton.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(resetCurrentColorButton);

        jPanel2.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);
        add(colorChooser, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton clearSearchButton;
    javax.swing.JColorChooser colorChooser;
    javax.swing.JTable colorStylesTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    javax.swing.JLabel matchCountLabel;
    javax.swing.JButton resetCurrentColorButton;
    private javax.swing.JEditorPane sampleEditorPane;
    private javax.swing.JPanel searchEastPanel;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchPanel;
    javax.swing.JTextField searchTextField;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
