plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = omegatModule.providedCoreLibsDir

dependencies {
    compileOnly(project(':'))
    if (providedCoreLibsDir.directory) {
        compileOnly omegatModule.providedCoreLib('jspecify', 'languagetool-core', 'commons-io')
        implementation omegatModule.providedModuleLib('language-ro')
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.languagetool.core)
        implementation(libs.languagetool.ro) {
            exclude module: 'languagetool-core'
        }
        compileOnly(libs.morfologik.stemming)
    }
    testImplementation(libs.junit4)
    testImplementation(libs.assertj.core)
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.commons.io)
    testImplementation(libs.languagetool.core)
    testImplementation project(":spellchecker:morfologik")
}

test {
    dependsOn tasks.withType(Jar)
    dependsOn project(":spellchecker:morfologik").tasks.withType(Jar)
}
