/**
 * Apertium translator connector.
 */

plugins {
    id 'org.omegat.module'
}

def providedCoreLibsDir = rootProject.property('providedCoreLibsDir')

dependencies {
    compileOnly(project(':'))
    if (file(providedCoreLibsDir).directory) {
        compileOnly fileTree(dir: providedCoreLibsDir, includes: ['**/jspecify-*.jar', '**/*commons-*.jar', '**/slf4j*.jar',
                                                                  '**/jackson*.jar'])
    } else {
        compileOnly(libs.commons.io)
        compileOnly(libs.jspecify)
        compileOnly(libs.commons.text)
        compileOnly(libs.slf4j.format.jdk14)
        // JSON parser
        compileOnly(libs.jackson.core)
        compileOnly(libs.jackson.databind)
    }
    testImplementation(testFixtures(project(':')))
    testImplementation(libs.jackson.core)
    testImplementation(libs.jackson.databind)
}
