/**************************************************************************
 OmegaT - Computer Assisted Translation (CAT) tool
          with fuzzy matching, translation memory, keyword search,
          glossaries, and translation leveraging into updated projects.

 Copyright (C) 2016 Aaron Madlon-Kay
               Home page: https://www.omegat.org/
               Support center: https://omegat.org/support

 This file is part of OmegaT.

 OmegaT is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OmegaT is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.
 **************************************************************************/

package org.omegat.gui.preferences.view;

import javax.swing.JPanel;

import org.omegat.util.OStrings;

/**
 * @author Aaron Madlon-Kay
 * @author Briac Pilpre
 */
@SuppressWarnings("serial")
public class PluginsPreferencesPanel extends JPanel {

    /** Creates new form PluginsPanel */
    public PluginsPreferencesPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelPluginsInfo = new javax.swing.JPanel();
        scrollTable = new javax.swing.JScrollPane();
        tablePluginsInfo = new javax.swing.JTable();
        panelPluginDetails = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        browsePluginsButton = new javax.swing.JButton();
        installFromDiskButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(250, 200));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setMaximumSize(new java.awt.Dimension(65534, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(200, 23));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        panelPluginsInfo.setLayout(new java.awt.GridLayout(1, 0));

        scrollTable.setPreferredSize(new java.awt.Dimension(452, 452));

        tablePluginsInfo.setAutoCreateRowSorter(true);
        tablePluginsInfo.setModel(new PluginInfoTableModel());
        scrollTable.setViewportView(tablePluginsInfo);

        panelPluginsInfo.add(scrollTable);

        jPanel1.add(panelPluginsInfo);

        panelPluginDetails.setLayout(new javax.swing.BoxLayout(panelPluginDetails, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel1.add(panelPluginDetails);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        org.openide.awt.Mnemonics.setLocalizedText(browsePluginsButton, OStrings.getString("PREFS_PLUGINS_BROWSE_ONLINE")); // NOI18N
        jPanel2.add(browsePluginsButton);

        org.openide.awt.Mnemonics.setLocalizedText(installFromDiskButton, OStrings.getString("PREFS_PLUGINS_INSTALL_FROM_DISK")); // NOI18N
        jPanel2.add(installFromDiskButton);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton browsePluginsButton;
    javax.swing.JButton installFromDiskButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    javax.swing.JPanel panelPluginDetails;
    private javax.swing.JPanel panelPluginsInfo;
    javax.swing.JScrollPane scrollTable;
    javax.swing.JTable tablePluginsInfo;
    // End of variables declaration//GEN-END:variables
}
