name: Check manuals build

on:
  push:
    branches:
      - master
      - releases/*
    paths:
      - 'build-logic/src/main/groovy/org.omegat.document-conventions.gradle'
      - 'src_docs/manual/**'
  pull_request:
    paths:
      - 'build-logic/src/main/groovy/org.omegat.document-conventions.gradle'
      - 'src_docs/manual/**'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: gradle/actions/setup-gradle@v4
      name: Setup Gradle
      id: setup-gradle
    - name: Run gradle manualsHtmls
      run: ./gradlew -PenvIsCi=true manualHtmls
      id: gradle
