name: Run PMD

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:

jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: create annotation
      run: echo "::add-matcher::${{ github.workspace }}/ci/github/problem-matcher.json"
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v4
    - name: run checkstyle
      run: ./gradlew -PenvIsCi pmdMain pmdTest
