name: Qodana
on:
  workflow_dispatch:
  schedule:
    - cron: '3 21 * * *'

concurrency:
  group: qodana-nightly
  cancel-in-progress: true

jobs:
  qodana:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
        name: Setup Gradle
        id: setup-gradle
      - name: Run gradle to generate sources
        run: ./gradlew genJAXB
        id: gradle
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          linter: jetbrains/qodana-jvm-community:2025.3
          pr-mode: false
          use-caches: true
          use-annotations: true
          upload-result: true
          args: --baseline,qodana.sarif.json